/**
 * Generated by sdk/scripts/extract-host-manifest.ts from host/host-main.cjs + host/version.
 * Do not edit by hand. Re-run: npm run extract-manifest
 */
export const HOST_MANIFEST = {
  "hostVersion": "0e82340",
  "capabilities": [
    "orderedReplicasV1",
    "sendAcceptanceV1"
  ],
  "commands": [
    "getTranscript",
    "getAgentTranscript",
    "getAgentTranscriptPage",
    "openAgentWindowed",
    "getAgentTranscriptWindow",
    "openAgentTail",
    "getAgentTranscriptTail",
    "getAgentThread",
    "sendPrompt",
    "promptAcceptanceStatus",
    "respondToWidget",
    "resolveAutoReviewApproval",
    "resolveLocalToolPermission",
    "dismissWidget",
    "submitSecret",
    "reactToMessage",
    "voteFeedback",
    "appendConnectorCard",
    "listAgents",
    "countAgents",
    "searchAgents",
    "searchMedia",
    "createAgent",
    "kickstartAgent",
    "interruptAgentRun",
    "requestDiskSaverAudit",
    "createGroup",
    "setGroupMembers",
    "updateAgent",
    "deleteAgent",
    "deleteAgents",
    "duplicateAgent",
    "setAgentUnread",
    "setAgentNotificationsEnabled",
    "setAgentNotifyOnUpdates",
    "setAgentHiddenFromSidebar",
    "openAgent",
    "setWindowFocused",
    "getAgentMemories",
    "deleteAgentMemory",
    "clearAgentMemories",
    "getAgentAutomations",
    "listAllAutomations",
    "isAgentNetworkEnabled",
    "isGlobalSearchEnabled",
    "isEgressTunnelAvailable",
    "getSharingState",
    "createRoomFromAgent",
    "createRoomInvite",
    "joinSharedRoom",
    "respondToRoomJoinRequest",
    "createSharedRoom",
    "addOwnAgentToSharedRoom",
    "removeOwnAgentFromSharedRoom",
    "setSharedRoomTyping",
    "leaveSharedRoom",
    "setAgentAutomationEnabled",
    "createAgentAutomation",
    "updateAgentAutomation",
    "deleteAgentAutomation",
    "runAgentAutomationNow",
    "broadcastToAgents",
    "getAgentWorkflows",
    "createAgentWorkflow",
    "updateAgentWorkflow",
    "setAgentWorkflowEnabled",
    "deleteAgentWorkflow",
    "runAgentWorkflowNow",
    "importAgentWorkflowText",
    "importAgentWorkflowUrl",
    "portAgentLocalSkills",
    "getConversationOutline",
    "skillsCatalog",
    "syncPluginSkills",
    "getPluginSyncStatus",
    "getSkillPublishTargets",
    "publishSkill",
    "resyncPublishedSkill",
    "unpublishSkill",
    "getAgentChannels",
    "connectChannel",
    "disconnectChannel",
    "refreshChannel",
    "getListenerIntegrations",
    "getListenerConnectUrl",
    "getSubagents",
    "getAsyncTasks",
    "setAgentAvatarBytes",
    "getAgentAvatar",
    "getAgentNotificationAvatar",
    "getForeverBoxStatus",
    "getCloudAgentInfo",
    "ensureForeverBox",
    "resetForeverBox",
    "updateForeverBox",
    "autoUpdateBoxNow",
    "snapshotBoxStoreNow",
    "getBoxStoreStatus",
    "clearBoxStoreNow",
    "updateHostNow",
    "getHostStatus",
    "setBoxMigrating",
    "prepareBoxForRecreate",
    "resumeBoxAfterRecreate",
    "handBackForeverBox",
    "startTeachRecording",
    "stopTeachRecording",
    "getTeachRecordingStatus",
    "getTrays",
    "dismissTray",
    "clearTrays",
    "uploadAttachment",
    "readAttachmentImage",
    "readAttachmentText",
    "readAttachmentChunk",
    "getHostSettings",
    "setHostSettings",
    "setBoxSecrets",
    "getBoxSecretsStatus",
    "completeMcpOAuth",
    "requestWebAuthnCeremony",
    "refreshMcp",
    "listBoxMcpServers"
  ],
  "wrappers": {
    "listAgents": {
      "inputKeys": []
    },
    "countAgents": {
      "inputKeys": []
    },
    "searchAgents": {
      "inputKeys": [
        "query",
        "limit"
      ]
    },
    "createAgent": {
      "inputKeys": [
        "name",
        "description",
        "title",
        "avatarShape",
        "avatarColor",
        "origin",
        "clientNonce",
        "isIntroductionSuppressed",
        "isKickstartRequested",
        "purpose",
        "templateId"
      ]
    },
    "updateAgent": {
      "inputKeys": [
        "id",
        "profile"
      ]
    },
    "deleteAgent": {
      "inputKeys": [
        "id"
      ]
    },
    "duplicateAgent": {
      "inputKeys": [
        "id"
      ]
    },
    "openAgent": {
      "inputKeys": [
        "id"
      ]
    },
    "setAgentUnread": {
      "inputKeys": [
        "id",
        "isUnread",
        "atMs"
      ]
    },
    "setAgentHiddenFromSidebar": {
      "inputKeys": [
        "id",
        "isHidden"
      ]
    },
    "setAgentNotificationsEnabled": {
      "inputKeys": [
        "id",
        "isEnabled"
      ]
    },
    "setAgentNotifyOnUpdates": {
      "inputKeys": [
        "id",
        "isEnabled"
      ]
    },
    "createGroup": {
      "inputKeys": [
        "name",
        "description",
        "memberAgentIds"
      ]
    },
    "setGroupMembers": {
      "inputKeys": [
        "id",
        "memberAgentIds"
      ]
    },
    "sendPrompt": {
      "inputKeys": [
        "prompt",
        "agentId",
        "attachmentPaths",
        "attachmentNames",
        "richText",
        "replyToId",
        "clientNonce",
        "directAddressedAcceptance",
        "isFork",
        "traceparent",
        "enterEpochMs",
        "composedAtMs"
      ]
    },
    "getTranscript": {
      "inputKeys": []
    },
    "getAgentTranscript": {
      "inputKeys": [
        "id"
      ]
    },
    "getAgentTranscriptPage": {
      "inputKeys": [
        "id",
        "limit",
        "beforeSeq",
        "sinceMs",
        "untilMs"
      ]
    },
    "getAgentTranscriptWindow": {
      "inputKeys": [
        "id",
        "limit",
        "beforeSeq"
      ]
    },
    "getAgentTranscriptTail": {
      "inputKeys": [
        "id",
        "limit",
        "beforeSeq"
      ]
    },
    "getAgentThread": {
      "inputKeys": [
        "id",
        "rootId"
      ]
    },
    "getConversationOutline": {
      "inputKeys": [
        "id"
      ]
    },
    "interruptAgentRun": {
      "inputKeys": [
        "id"
      ]
    },
    "respondToWidget": {
      "inputKeys": [
        "entryId",
        "value",
        "agentId"
      ]
    },
    "dismissWidget": {
      "inputKeys": [
        "entryId",
        "agentId"
      ]
    },
    "reactToMessage": {
      "inputKeys": [
        "entryId",
        "emoji",
        "agentId"
      ]
    },
    "getAgentMemories": {
      "inputKeys": [
        "id"
      ]
    },
    "deleteAgentMemory": {
      "inputKeys": [
        "id",
        "memoryId"
      ]
    },
    "clearAgentMemories": {
      "inputKeys": [
        "id"
      ]
    },
    "getAgentAutomations": {
      "inputKeys": [
        "id"
      ]
    },
    "listAllAutomations": {
      "inputKeys": []
    },
    "createAgentAutomation": {
      "inputKeys": [
        "id",
        "spec"
      ]
    },
    "updateAgentAutomation": {
      "inputKeys": [
        "id",
        "automationId",
        "spec"
      ]
    },
    "deleteAgentAutomation": {
      "inputKeys": [
        "id",
        "automationId"
      ]
    },
    "setAgentAutomationEnabled": {
      "inputKeys": [
        "id",
        "automationId",
        "isEnabled"
      ]
    },
    "runAgentAutomationNow": {
      "inputKeys": [
        "id",
        "automationId"
      ]
    },
    "getAgentWorkflows": {
      "inputKeys": [
        "id"
      ]
    },
    "createAgentWorkflow": {
      "inputKeys": [
        "id",
        "spec"
      ]
    },
    "updateAgentWorkflow": {
      "inputKeys": [
        "id",
        "workflowId",
        "spec"
      ]
    },
    "deleteAgentWorkflow": {
      "inputKeys": [
        "id",
        "workflowId"
      ]
    },
    "setAgentWorkflowEnabled": {
      "inputKeys": [
        "id",
        "workflowId",
        "isEnabled"
      ]
    },
    "runAgentWorkflowNow": {
      "inputKeys": [
        "id",
        "workflowId"
      ]
    },
    "skillsCatalog": {
      "inputKeys": []
    },
    "broadcastToAgents": {
      "inputKeys": [
        "targets",
        "message"
      ]
    },
    "searchMedia": {
      "inputKeys": [
        "query",
        "limit"
      ]
    },
    "getHostSettings": {
      "inputKeys": []
    },
    "getHostStatus": {
      "inputKeys": []
    },
    "getForeverBoxStatus": {
      "inputKeys": [
        "id"
      ]
    },
    "promptAcceptanceStatus": {
      "inputKeys": [
        "accountSlot",
        "clientNonce"
      ]
    },
    "kickstartAgent": {
      "inputKeys": [
        "id"
      ]
    },
    "getAgentChannels": {
      "inputKeys": [
        "id"
      ]
    },
    "getSubagents": {
      "inputKeys": [
        "id"
      ]
    },
    "getAsyncTasks": {
      "inputKeys": [
        "id"
      ]
    },
    "isAgentNetworkEnabled": {
      "inputKeys": []
    },
    "isGlobalSearchEnabled": {
      "inputKeys": []
    },
    "isEgressTunnelAvailable": {
      "inputKeys": []
    },
    "getAgentAvatar": {
      "inputKeys": [
        "id"
      ]
    },
    "requestDiskSaverAudit": {
      "inputKeys": [
        "id"
      ]
    },
    "listBoxMcpServers": {
      "inputKeys": [
        "serverIdentifiers"
      ]
    },
    "getPluginSyncStatus": {
      "inputKeys": []
    },
    "getListenerIntegrations": {
      "inputKeys": []
    },
    "getListenerConnectUrl": {
      "inputKeys": [
        "platform"
      ]
    },
    "getBoxStoreStatus": {
      "inputKeys": []
    },
    "openAgentWindowed": {
      "inputKeys": [
        "id",
        "limit"
      ]
    },
    "openAgentTail": {
      "inputKeys": [
        "id",
        "limit"
      ]
    },
    "importAgentWorkflowText": {
      "inputKeys": [
        "id",
        "markdown",
        "name"
      ]
    },
    "importAgentWorkflowUrl": {
      "inputKeys": [
        "id",
        "url",
        "name"
      ]
    },
    "portAgentLocalSkills": {
      "inputKeys": [
        "id"
      ]
    }
  },
  "notes": {
    "commands": "Generated from host/host-main.cjs SAND_GATEWAY_COMMANDS keys.",
    "capabilities": "Generated from host/host-main.cjs HOST_CAPABILITIES.",
    "wrapperInputKeys": "Hand-cited from TypedCommandMap in sdk/src/gateway/commands.ts. The host snapshot has no listCommands API and no per-command JSON schema table."
  }
} as const;
