/**
 * Extract a small host-contract manifest from a local host snapshot (not in this repo).
 * Host wins: command names + version come from host/host-main.cjs + host/version.
 * Wrapper input keys are hand-cited from TypedCommandMap (no host schema table).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { TYPED_WRAPPER_INPUT_KEYS } from "../src/gateway/commands.js";

export const HOST_COMMANDS_START = "var SAND_GATEWAY_COMMANDS = {";
export const HOST_COMMANDS_END = "var SAND_GATEWAY_SLIM_COMMANDS";
export const HOST_CAPABILITIES_DECL = "var HOST_CAPABILITIES = [";

export type HostManifest = {
  hostVersion: string;
  capabilities: string[];
  commands: string[];
  wrappers: Record<string, { inputKeys: string[] }>;
  notes: {
    commands: string;
    capabilities: string;
    wrapperInputKeys: string;
  };
};

export function extractHostVersion(versionText: string): string {
  const version = versionText.trim();
  if (version.length === 0) {
    throw new Error("host version file is empty");
  }
  if (version.includes("\n")) {
    throw new Error("host version must be a single trimmed line");
  }
  return version;
}

export function extractGatewayCommandNames(hostMainSource: string): string[] {
  const start = hostMainSource.indexOf(HOST_COMMANDS_START);
  const slim = hostMainSource.indexOf(HOST_COMMANDS_END);
  if (start < 0) throw new Error("host SAND_GATEWAY_COMMANDS table not found");
  if (slim <= start) throw new Error("host SAND_GATEWAY_SLIM_COMMANDS marker not found");
  const block = hostMainSource.slice(start, slim);
  const names = [...block.matchAll(/^\s{2}([A-Za-z][A-Za-z0-9]*):/gm)].map(
    (match) => match[1]!,
  );
  if (names.length === 0) throw new Error("no command names extracted from host table");
  return names;
}

function resolveHostStringConst(source: string, ident: string): string | null {
  const match = source.match(new RegExp(`var ${ident} = "([^"]+)"`));
  return match?.[1] ?? null;
}

export function extractHostCapabilities(hostMainSource: string): string[] {
  const start = hostMainSource.indexOf(HOST_CAPABILITIES_DECL);
  if (start < 0) throw new Error("host HOST_CAPABILITIES not found");
  const end = hostMainSource.indexOf("];", start);
  if (end < 0) throw new Error("host HOST_CAPABILITIES array is unclosed");
  const inner = hostMainSource.slice(start + HOST_CAPABILITIES_DECL.length, end);
  const tokens = [...inner.matchAll(/"([^"]+)"|([A-Za-z_][A-Za-z0-9_]*)/g)];
  if (tokens.length === 0) throw new Error("host HOST_CAPABILITIES is empty");
  return tokens.map((token) => {
    if (token[1] != null) return token[1];
    const ident = token[2]!;
    const resolved = resolveHostStringConst(hostMainSource, ident);
    if (resolved == null) {
      throw new Error(`could not resolve HOST_CAPABILITIES identifier ${ident}`);
    }
    return resolved;
  });
}

export function wrapperCoverageFromKeys(
  keys: Record<string, readonly string[]>,
): Record<string, { inputKeys: string[] }> {
  const wrappers: Record<string, { inputKeys: string[] }> = {};
  for (const [name, inputKeys] of Object.entries(keys)) {
    wrappers[name] = { inputKeys: [...inputKeys] };
  }
  return wrappers;
}

export function buildHostManifest(input: {
  hostMainSource: string;
  hostVersionText: string;
  wrapperInputKeys?: Record<string, readonly string[]>;
}): HostManifest {
  return {
    hostVersion: extractHostVersion(input.hostVersionText),
    capabilities: extractHostCapabilities(input.hostMainSource),
    commands: extractGatewayCommandNames(input.hostMainSource),
    wrappers: wrapperCoverageFromKeys(
      input.wrapperInputKeys ?? TYPED_WRAPPER_INPUT_KEYS,
    ),
    notes: {
      commands: "Generated from host/host-main.cjs SAND_GATEWAY_COMMANDS keys.",
      capabilities: "Generated from host/host-main.cjs HOST_CAPABILITIES.",
      wrapperInputKeys:
        "Hand-cited from TypedCommandMap in sdk/src/gateway/commands.ts. The host snapshot has no listCommands API and no per-command JSON schema table.",
    },
  };
}

export function formatHostManifest(manifest: HostManifest): string {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

export function renderHostManifestModule(manifest: HostManifest): string {
  return [
    "/**",
    " * Generated by sdk/scripts/extract-host-manifest.ts from host/host-main.cjs + host/version.",
    " * Do not edit by hand. Re-run: npm run extract-manifest",
    " */",
    `export const HOST_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;`,
    "",
  ].join("\n");
}

export function defaultHostPaths(fromDir: string = dirname(fileURLToPath(import.meta.url))): {
  hostMainPath: string;
  hostVersionPath: string;
  outputPath: string;
} {
  const repoRoot = join(fromDir, "..", "..");
  return {
    hostMainPath: join(repoRoot, "host", "host-main.cjs"),
    hostVersionPath: join(repoRoot, "host", "version"),
    outputPath: join(fromDir, "..", "src", "gateway", "host-manifest.generated.ts"),
  };
}

export function extractHostManifestFromFiles(paths = defaultHostPaths()): HostManifest {
  return buildHostManifest({
    hostMainSource: readFileSync(paths.hostMainPath, "utf8"),
    hostVersionText: readFileSync(paths.hostVersionPath, "utf8"),
  });
}

export function writeHostManifest(paths = defaultHostPaths()): HostManifest {
  const manifest = extractHostManifestFromFiles(paths);
  writeFileSync(paths.outputPath, renderHostManifestModule(manifest));
  return manifest;
}

const invokedAsCli =
  process.argv[1] != null &&
  fileURLToPath(import.meta.url) === resolve(process.argv[1]);

if (invokedAsCli) {
  const manifest = writeHostManifest();
  process.stdout.write(
    `wrote ${manifest.commands.length} commands for hostVersion=${manifest.hostVersion}\n`,
  );
}
