export {
  DEFAULT_GATEWAY_TIMEOUT_MS,
  DISCOVERY_COMMAND,
  GrokBot,
  GrokBotGatewayError,
  discoveryFailureHint,
  parseSseBlock,
} from "./gateway/client.js";
export { parseConversationOutline, outlineThinkingSteps } from "./gateway/outline.js";
export { parseHostModelSelection } from "./gateway/host-model.js";
export { isAgentIdRef, resolveAgentId } from "./gateway/resolve-agent.js";
export type { AgentNameRow, ResolveAgentOptions } from "./gateway/resolve-agent.js";
export { TOKEN_USAGE_NOTE, collectDigest, formatDigest } from "./digest.js";
export type {
  DigestAutomationRow,
  DigestListenerRow,
  DigestRosterRow,
  DigestThinkingRow,
  DigestView,
} from "./digest.js";
export type { GatewayRequestOptions, GrokBotOptions } from "./gateway/client.js";
export { evaluateCompat, formatCompatVerdict } from "./gateway/compat.js";
export type { CompatLiveStatus, CompatVerdict, HostVersionStatus } from "./gateway/compat.js";
export { HOST_MANIFEST } from "./gateway/host-manifest.generated.js";
export {
  CREATE_AGENT_DEFAULT_NAME_PREFIX,
  DEFAULT_RUN_ONCE_TIMEOUT_MS,
  DEFAULT_WAIT_FOR_IDLE_INTERVAL_MS,
  DISCUSS_ONCE_DEFAULT_NAME_PREFIX,
  SEND_AS_AGENT_DEFAULT_NAME_PREFIX,
  completeSendPromptWait,
  discussOnce,
  entriesFromTranscriptPayload,
  formatDiscussReceipt,
  formatDiscussTurns,
  formatOneShotReceipt,
  formatSendAsAgentReceipt,
  lastAssistantTextFromEntries,
  resolveCreateAgentDescription,
  resolveCreateAgentName,
  resolveDiscussOnceName,
  resolveSendAsAgentName,
  runOnce,
  runOnceDiscuss,
  runOnceFrom,
  runOnceLike,
  runOnceSendToAgent,
  sendAsAgent,
  sendAsAgentPrompt,
  toHostCreateAgentBody,
  toHostSendPromptBody,
  turnsFromTranscriptEntries,
  waitForIdle,
} from "./gateway/oneshot.js";
export type {
  DiscussOnceInput,
  DiscussOnceReceipt,
  DiscussTurn,
  OneShotClient,
  OneShotReceipt,
  OneShotStatus,
  RunOnceFromInput,
  RunOnceInput,
  SendAsAgentInput,
  SendAsAgentReceipt,
  SendPromptCallInput,
  SendPromptWaitResult,
  WaitForIdleInput,
  WaitForIdleResult,
} from "./gateway/oneshot.js";
export {
  DESTRUCTIVE_GATEWAY_COMMANDS,
  GATEWAY_API_PREFIX,
  GATEWAY_AUTH_SCHEME,
  GATEWAY_AVATARS_PATH,
  GATEWAY_EVENTS_PATH,
  GATEWAY_HEALTH_PATH,
  GATEWAY_REQUEST_ID_HEADER,
  GATEWAY_SLIM_AVATARS_HEADER,
  SAND_GATEWAY_COMMANDS,
  TYPED_WRAPPER_INPUT_KEYS,
  UNSAFE_GATEWAY_COMMANDS,
  assertGatewayCommandAllowed,
  isUnsafeGatewayCommand,
} from "./gateway/commands.js";
export type {
  AgentIdBody,
  AgentThreadInput,
  AutomationIdInput,
  AutomationSpec,
  BroadcastInput,
  CreateAgentInput,
  CreateAutomationInput,
  CreateGroupInput,
  CreateWorkflowInput,
  DeleteMemoryInput,
  DestructiveGatewayCommand,
  UnsafeGatewayCommand,
  DismissWidgetInput,
  ForeverBoxStatusInput,
  GatewayCommandName,
  ImportWorkflowTextInput,
  ImportWorkflowUrlInput,
  ListBoxMcpServersInput,
  ListenerConnectUrlInput,
  OpenAgentBoundedInput,
  ReactToMessageInput,
  SearchQueryInput,
  SetAutomationEnabledInput,
  SetGroupMembersInput,
  SetHiddenInput,
  SetNotifyInput,
  SetUnreadInput,
  SetWorkflowEnabledInput,
  TranscriptPageInput,
  TranscriptWindowInput,
  TypedCommandMap,
  UpdateAgentInput,
  UpdateAutomationInput,
  UpdateWorkflowInput,
  WidgetResponseInput,
  WorkflowIdInput,
  WorkflowSpec,
} from "./gateway/commands.js";
export {
  connectHostFor,
  discoverGateway,
  formatDiscoveryOutput,
  formatHealthOutput,
  normalizeGatewayBaseUrl,
  publicDiscovery,
  redactSecret,
} from "./gateway/discovery.js";
export type { DiscoverOptions, ResolvedGateway } from "./gateway/discovery.js";

export { GrokBotDisk } from "./disk/index.js";
export {
  AUTOMATION_CONFIG_FILENAME,
  AUTOMATION_MAX_NAME_LENGTH,
  AgentStore,
  BRANCHED_ENTRY_FILTER_SQL,
  CONVERSATION_BLOB_SCHEMA,
  DEFAULT_HIDDEN_FROM_SIDEBAR,
  DEFAULT_NOTIFY_ON_AGENT_UPDATES,
  FACT_LINE,
  GROUP_CONFIG_VERSION,
  GROUP_MAX_MEMBERS,
  LOG_HEADER,
  MAIN_TRANSCRIPT_MESSAGE_FILTER_SQL,
  MEMORY_EPISODE_PREFIX,
  MEMORY_MAX_CONTENT_LENGTH,
  MEMORY_NOTE_PREFIX,
  PROFILE_HEADER,
  ROUTINE_NOTICE_IDS,
  STORE_ENTRY_KINDS,
  STORE_KV_KEYS,
  STORE_SCHEMA,
  SearchIndex,
  TRANSCRIPT_NON_MESSAGE_TYPES,
  WINDOW_ENTRY_FILTER_SQL,
  forgetMemoryFact,
  formatLegacyTranscriptLine,
  formatMemoryDate,
  isLegacyTranscriptEnvelope,
  listAgentAutomations,
  listAllDiskAutomations,
  listDiskAgents,
  listGlobalWorkflows,
  listMemoryFacts,
  listTranscriptFiles,
  memoryDedupeKey,
  memoryIdFor,
  normalizeMemoryContent,
  openAgentStore,
  openSearchIndex,
  parseFacts,
  parseLegacyTranscriptLine,
  parseSandGroup,
  parseSandProfile,
  parseSandSettings,
  parseStoredAutomationConfig,
  readActiveAgentId,
  readGroup,
  readProfile,
  readSettings,
  readTranscript,
  resolveDiskAgent,
  serializeFactLine,
  summarizeContent,
  writeMemoryFact,
} from "./disk/index.js";
export type {
  DiskAgent,
  ForgetMemoryInput,
  ReadTranscriptOptions,
  SearchMediaQuery,
  SearchMessageQuery,
  TranscriptIndexEntry,
  WriteMemoryInput,
} from "./disk/index.js";

export {
  AGENT_DATA_ALIAS,
  DEFAULT_SAND_ROOT,
  ENV_GROKBOT_GATEWAY_URL,
  ENV_GROKBOT_JOBS_DIR,
  ENV_GROKBOT_LIVE,
  ENV_SAND_DATA_ROOT,
  ENV_SAND_GATEWAY_BIND_HOST,
  ENV_SAND_GATEWAY_TOKEN,
  ENV_SAND_GATEWAY_URL,
  ENV_SAND_HOST_PORT,
  ENV_SAND_USER_DATA_DIR,
  activeAgentPath,
  agentDir,
  agentMemoryDir,
  agentsDir,
  conversationBlobsPath,
  gatewayDiscoveryPath,
  isSafeFolderId,
  isValidSandAgentId,
  resolveJobsDir,
  resolveSandRoot,
  resolveSafeChildDir,
  sandPaths,
  searchIndexPath,
  storeDbPath,
  transcriptPath,
  userMemoryShardDir,
  workflowsDir,
  SandInvalidAgentIdError,
  assertValidSandAgentId,
} from "./paths.js";
export type { SandPaths } from "./paths.js";

export {
  DEFAULT_ACTIONS_FORBIDDEN,
  JOB_AWAITING_USER,
  JOB_ISOLATIONS,
  JOB_JSON_SCHEMA,
  JOB_MODES,
  JOB_SCHEMA_VERSION,
  JOB_SIDE_EFFECTS,
  JOB_STATUSES,
  JobValidationError,
  JOB_DISCUSS_ONCE_DESCRIPTION,
  formatJobList,
  formatJobRecord,
  formatJobTurns,
  getJob,
  jobDiscussOnceName,
  jobRecordPath,
  listJobs,
  mergeForbiddenActions,
  packetMayIncludeApply,
  readJobRecord,
  runJob,
  submitJob,
  validateJob,
  writeJobRecord,
} from "./job/index.js";
export type {
  DefaultForbiddenAction,
  Job,
  JobAwaitingUser,
  JobClient,
  JobCompatNote,
  JobIsolation,
  JobMode,
  JobPacket,
  JobQuietHours,
  JobRecord,
  JobSideEffect,
  JobSource,
  JobStatus,
  JobTurn,
  SubmitJobOptions,
} from "./job/index.js";

export { HOST_ACCOUNT_SLOT } from "./types.js";
export type * from "./types.js";
